# Generated by Django 2.1.5 on 2019-12-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.TextField(blank=True, null=True)),
                ('number', models.DecimalField(decimal_places=0, max_digits=1000)),
                ('workshops', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
